"""
Defines constants that are used throughout the game
"""
WIDTH = 1200
HEIGHT = 690
FPS = 60
PAUSED_FPS = 30

HALF_WIDTH = WIDTH/2
HALF_HEIGHT = HEIGHT/2

PLAYER_ARROW_SET_X = (HALF_WIDTH/2)*3
ENEMY_ARROW_SET_X = HALF_WIDTH/2

MESSAGE_X = HALF_WIDTH
MESSAGE_1_Y = HALF_HEIGHT - 150
MESSAGE_2_Y = HALF_HEIGHT 
MESSAGE_3_Y = HALF_HEIGHT + 150

TITLE_SIZE = 100
TITLE_SIZE_2 = 75
TITLE_SIZE_3 = 50
MENU_SCORE = 20

GOOD_EARNED = 25
SICK_EARNED = 60